right_hip_yaw: 1 

left_hip_yaw: 2 

right_hip_roll: 3 

left_hip_roll: 4 

right_hip_pitch: 5 

left_hip_pitch: 6 

right_knee: 7 

left_knee: 8 

right_ankle_pitch: 9 

left_ankle_pitch: 10 

right_ankle_roll: 11 

left_ankle_roll: 12 
