left_hip_yaw : 1
right_hip_yaw : 2

left_hip_roll : 3
right_hip_roll : 4

left_hip_pitch : 5
right_hip_pitch : 6

left_knee : 7
right_knee : 8

left_ankle_pitch : 9
right_ankle_pitch : 10

left_ankle_roll : 11
right_ankle_roll : 12
